# Generated by Django 2.1 on 2019-06-11 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
