# Generated by Django 2.1 on 2019-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190611_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='blog.Post'),
        ),
    ]
