# Generated by Django 2.1 on 2019-06-11 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_hearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hearts',
        ),
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
